<a href="https://colab.research.google.com/github/leehj112/Data-Analyses/blob/master/colab_exDense.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import layers

class exDense(layers.Layer):

  def __init__(self, units=32):
      super(exDense, self).__init__()
      self.units = units

  def build(self, input_shape):
    w_init = tf.random_normal_initializer()
    self.w = tf.Variable(
        initial_value=w_init(shape=(input_shape[-1], self.units),
                             dtype='float32'), trainable=True, name="weight")
    b_init = tf.ones_initializer()
    self.b = tf.Variable(
        initial_value=b_init(shape=(self.units,), dtype='float32'),
        trainable=False, name="bias")

  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b

In [2]:
# 레이어 인스턴스 생성.
exDense_layer = exDense(4)

# build() 호출 전의 가중치 확인
before_w = exDense_layer.weights
print("all weights(before)", before_w)

# 입력 데이터 대입 및 결과 반환
out = exDense_layer(tf.ones((3, 3)))
print("\noutputs:", out)

# build() 호출 후의 가중치 확인
after_w = exDense_layer.weights
print("\nall weights(after)", after_w)

all weights(before) []

outputs: tf.Tensor(
[[0.98953885 0.9668753  0.98656106 1.0069402 ]
 [0.98953885 0.9668753  0.98656106 1.0069402 ]
 [0.98953885 0.9668753  0.98656106 1.0069402 ]], shape=(3, 4), dtype=float32)

all weights(after) [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.00607165,  0.01810046, -0.07381652,  0.03056382],
       [ 0.02299245, -0.05909666,  0.03664998, -0.04101245],
       [-0.02738198,  0.00787152,  0.02372762,  0.01738882]],
      dtype=float32)>, <tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]


In [3]:
t_w = exDense_layer.trainable_weights
print("\ntraninable_weights", t_w)

nt_w = exDense_layer.non_trainable_weights
print("\nnon_traninable_weights", nt_w)

t_v = exDense_layer.trainable_variables
print("\ntraninable_variables", t_v)

nt_v = exDense_layer.non_trainable_variables
print("\nnon_traninable_variables", nt_v)



traninable_weights [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.00607165,  0.01810046, -0.07381652,  0.03056382],
       [ 0.02299245, -0.05909666,  0.03664998, -0.04101245],
       [-0.02738198,  0.00787152,  0.02372762,  0.01738882]],
      dtype=float32)>]

non_traninable_weights [<tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]

traninable_variables [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[-0.00607165,  0.01810046, -0.07381652,  0.03056382],
       [ 0.02299245, -0.05909666,  0.03664998, -0.04101245],
       [-0.02738198,  0.00787152,  0.02372762,  0.01738882]],
      dtype=float32)>]

non_traninable_variables [<tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([1., 1., 1., 1.], dtype=float32)>]


In [4]:
import tensorflow as tf
from tensorflow.keras import layers

class exDense(layers.Layer):

  def __init__(self, units=32):
      super(exDense, self).__init__()
      self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(shape=(input_shape[-1], self.units),
                          initializer='random_normal',
                          trainable=True, name="weight")
    self.b = self.add_weight(shape=(self.units,),
                              initializer='random_normal',
                              trainable=True, name="bias")
  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b