<a href="https://colab.research.google.com/github/leehj112/Data-Analyses/blob/master/colab_init_weight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf
from tensorflow.keras import initializers

norm_init1 = tf.keras.initializers.RandomNormal(mean=0., stddev=1.)
norm_init2 = tf.keras.initializers.RandomNormal(mean=0., stddev=1., seed=100)

for i in range(3):
  values1 = norm_init1(shape=(2, 2)).numpy()
  values2 = norm_init2(shape=(2, 2)).numpy()
  print(i, "initializer1 : ", values1)
  print(i, "initializer2 : ", values2)

0 initializer1 :  [[ 0.830678  -1.2148647]
 [ 0.7490029 -0.7047204]]
0 initializer2 :  [[ 1.7098777  -0.12379249]
 [-1.8377445   0.4658048 ]]
1 initializer1 :  [[ 0.830678  -1.2148647]
 [ 0.7490029 -0.7047204]]
1 initializer2 :  [[ 1.7098777  -0.12379249]
 [-1.8377445   0.4658048 ]]
2 initializer1 :  [[ 0.830678  -1.2148647]
 [ 0.7490029 -0.7047204]]
2 initializer2 :  [[ 1.7098777  -0.12379249]
 [-1.8377445   0.4658048 ]]


In [6]:
# 레이어 인스턴스 생성.
exDense_layer = exDense(4)

# build() 호출 전의 가중치 확인
before_w = exDense_layer.weights
print("all weights(before)", before_w)

# 입력 데이터 대입 및 결과 반환
out = exDense_layer(tf.ones((3, 3)))
print("\noutputs:", out)

# build() 호출 후의 가중치 확인
after_w = exDense_layer.weights
print("\nall weights(after)", after_w)

all weights(before) []

outputs: tf.Tensor(
[[ 0.09471354 -0.024614   -0.04051714 -0.12183122]
 [ 0.09471354 -0.024614   -0.04051714 -0.12183122]
 [ 0.09471354 -0.024614   -0.04051714 -0.12183122]], shape=(3, 4), dtype=float32)

all weights(after) [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.00776082,  0.02504162,  0.09348115, -0.07358729],
       [-0.06918194,  0.02467989,  0.01830942,  0.10020339],
       [ 0.09459344, -0.08853202, -0.01372014, -0.11219593]],
      dtype=float32)>, <tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([ 0.06154121,  0.0141965 , -0.13858756, -0.03625138], dtype=float32)>]


In [7]:

t_w = exDense_layer.trainable_weights
print("\ntraninable_weights", t_w)

nt_w = exDense_layer.non_trainable_weights
print("\nnon_traninable_weights", nt_w)

t_v = exDense_layer.trainable_variables
print("\ntraninable_variables", t_v)

nt_v = exDense_layer.non_trainable_variables
print("\nnon_traninable_variables", nt_v)



traninable_weights [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.00776082,  0.02504162,  0.09348115, -0.07358729],
       [-0.06918194,  0.02467989,  0.01830942,  0.10020339],
       [ 0.09459344, -0.08853202, -0.01372014, -0.11219593]],
      dtype=float32)>, <tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([ 0.06154121,  0.0141965 , -0.13858756, -0.03625138], dtype=float32)>]

non_traninable_weights []

traninable_variables [<tf.Variable 'ex_dense/weight:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.00776082,  0.02504162,  0.09348115, -0.07358729],
       [-0.06918194,  0.02467989,  0.01830942,  0.10020339],
       [ 0.09459344, -0.08853202, -0.01372014, -0.11219593]],
      dtype=float32)>, <tf.Variable 'ex_dense/bias:0' shape=(4,) dtype=float32, numpy=array([ 0.06154121,  0.0141965 , -0.13858756, -0.03625138], dtype=float32)>]

non_traninable_variables []


In [8]:
import tensorflow as tf
from tensorflow.keras import layers

class exDense(layers.Layer):

  def __init__(self, units=32):
      super(exDense, self).__init__()
      self.units = units

  def build(self, input_shape):
    self.w = self.add_weight(shape=(input_shape[-1], self.units),
                          initializer='random_normal',
                          trainable=True, name="weight")
    self.b = self.add_weight(shape=(self.units,),
                              initializer='random_normal',
                              trainable=True, name="bias")
  def call(self, inputs):
      return tf.matmul(inputs, self.w) + self.b