<a href="https://colab.research.google.com/github/leehj112/Data-Analyses/blob/master/colab_pooling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

x = tf.constant([1., 3., 5., 7., 9., 2., 4., 6., 8., 10.])
x1 = tf.reshape(x, [1, 5, 2])
maxpool1d = tf.keras.layers.MaxPooling1D(pool_size=2, strides=1,
                                         padding='valid')(x1)

print("input : ", x1)
print("\nmax pooling 1d : " ,maxpool1d)

input :  tf.Tensor(
[[[ 1.  3.]
  [ 5.  7.]
  [ 9.  2.]
  [ 4.  6.]
  [ 8. 10.]]], shape=(1, 5, 2), dtype=float32)

max pooling 1d :  tf.Tensor(
[[[ 5.  7.]
  [ 9.  7.]
  [ 9.  6.]
  [ 8. 10.]]], shape=(1, 4, 2), dtype=float32)


In [2]:

x2 = tf.reshape(x, [1, 2, 5])
averagepool1d = tf.keras.layers.AveragePooling1D(pool_size=2, strides=1,
                                             padding='same')(x2)
print("input : ", x2)
print("\nAverage pooling 1d : " ,averagepool1d)

input :  tf.Tensor(
[[[ 1.  3.  5.  7.  9.]
  [ 2.  4.  6.  8. 10.]]], shape=(1, 2, 5), dtype=float32)

Average pooling 1d :  tf.Tensor(
[[[ 1.5  3.5  5.5  7.5  9.5]
  [ 2.   4.   6.   8.  10. ]]], shape=(1, 2, 5), dtype=float32)


In [3]:
globalmaxpool1d = tf.keras.layers.GlobalMaxPooling1D()(x2)
globalaveragepool1d = tf.keras.layers.GlobalAveragePooling1D()(x2)

print("Global max pooling 1d : " ,globalmaxpool1d)
print("\nGlobal average pooling 1d : " ,globalaveragepool1d)

Global max pooling 1d :  tf.Tensor([[ 2.  4.  6.  8. 10.]], shape=(1, 5), dtype=float32)

Global average pooling 1d :  tf.Tensor([[1.5 3.5 5.5 7.5 9.5]], shape=(1, 5), dtype=float32)
