<a href="https://colab.research.google.com/github/leehj112/Data-Analyses/blob/master/colab_conv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import tensorflow as tf

input_shape = (3, 2, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(
    filters=1, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[ 0.04054786]
  [-1.725868  ]]

 [[ 0.5136989 ]
  [ 0.6046323 ]]

 [[ 0.5541079 ]
  [-0.5326651 ]]], shape=(3, 2, 1), dtype=float32)

conv1D :  tf.Tensor(
[[[-1.6853201 ]]

 [[ 1.1183312 ]]

 [[ 0.02144283]]], shape=(3, 1, 1), dtype=float32)


In [2]:
input_shape = (3, 3, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv1D(
    filters=2, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[-0.04301258]
  [ 0.5953605 ]
  [-0.50441927]]

 [[ 0.36562672]
  [ 0.9375814 ]
  [ 0.1324549 ]]

 [[ 0.26523903]
  [ 0.48049906]
  [ 1.243706  ]]], shape=(3, 3, 1), dtype=float32)

conv1D :  tf.Tensor(
[[[0.55234796 0.55234796]
  [0.09094125 0.09094125]]

 [[1.3032081  1.3032081 ]
  [1.0700363  1.0700363 ]]

 [[0.7457381  0.7457381 ]
  [1.724205   1.724205  ]]], shape=(3, 2, 2), dtype=float32)


In [3]:
input_shape = (3, 5, 5, 1)
x = tf.random.normal(input_shape)
y = tf.keras.layers.Conv2D(
    filters=2, kernel_size=2, activation=None, kernel_initializer = 'ones',
    input_shape=input_shape[1:])(x)

print("input ", x)
print("\nconv1D : ", y)

input  tf.Tensor(
[[[[-0.41906673]
   [ 1.6465174 ]
   [-0.922565  ]
   [-0.15546729]
   [-0.934638  ]]

  [[-0.5108723 ]
   [-0.68295324]
   [-0.08908749]
   [-0.5662364 ]
   [ 1.1995462 ]]

  [[-0.5887277 ]
   [-0.50310296]
   [ 1.8789274 ]
   [ 0.2219685 ]
   [ 0.621223  ]]

  [[-0.40476412]
   [ 0.35219365]
   [ 0.5428564 ]
   [ 0.08342744]
   [ 0.20189479]]

  [[ 0.46978134]
   [-1.2526145 ]
   [-0.23219189]
   [-1.3519833 ]
   [-0.11230814]]]


 [[[-1.8390934 ]
   [ 0.6903155 ]
   [-0.03228209]
   [-0.38756275]
   [ 1.6515834 ]]

  [[ 0.36521044]
   [-1.0486064 ]
   [ 1.2136205 ]
   [-0.1778224 ]
   [ 0.92490697]]

  [[ 0.4179284 ]
   [-0.5202286 ]
   [-1.7081549 ]
   [ 0.69285405]
   [ 0.11405782]]

  [[-0.08848488]
   [-0.39157203]
   [-0.88463247]
   [ 1.5552047 ]
   [-1.1224258 ]]

  [[-0.15998353]
   [ 0.52561665]
   [ 0.80118173]
   [-1.178547  ]
   [ 0.5593425 ]]]


 [[[-0.5799219 ]
   [-0.7010584 ]
   [-0.00341049]
   [-0.22075914]
   [ 0.4909973 ]]

  [[ 0.6229956 ]
   [